GRID_SIZE = (30, 30, 10)
DEPOT_POS = (0,0,0)#(GRID_SIZE[0] - 1, GRID_SIZE[1] - 1, 0)
NUM_ROBOTS = 10
STEP_DELAY = 0.01
STRUCTURES = ["overhangs"] # ["random"]
RANDOM_VOXELS = 20
RANDOM_STRUCTURE_ORIGINS = 1
SCAFFOLDING = True